source 'https://rubygems.org'

gem 'rails', '4.2.6'
# gem 'sqlite3'
gem 'mysql2'
gem 'unicorn'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'dalli', '2.6.4'
gem 'figaro'
gem 'therubyracer'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pry-doc'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem "better_errors"
  gem "binding_of_caller"
  gem 'thin'
  gem 'quiet_assets'
end
